#!/bin/sh

# inspired by http://samrowe.com/wordpress/ssh-agent-and-gnu-screen/
# with more escaping, avoiding sed

SSHV="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

for x in ${SSHV} ; do
    (eval echo export $x=\\\'\$$x\\\')
done 1>$HOME/bin/fixssh
